"""Daily memory synchronization tools for the Partenon Brain."""

from typing import Any

from .gbrain_client import GBrainClient


def _client() -> GBrainClient:
    return GBrainClient()


def collect_learnings(since_hours: int = 24) -> dict[str, Any]:
    """Gather learnings generated by each hero in the last N hours."""
    return {"ok": True, "since_hours": since_hours, "learnings": []}


def collect_decisions(status: str = "validated") -> dict[str, Any]:
    """Gather decisions marked as validated by the operator or by heroes."""
    return {"ok": True, "status": status, "decisions": []}


def index_in_gbrain(items: list[dict[str, Any]]) -> dict[str, Any]:
    """Index a batch of items in G-Brain with proper tags and relationships."""
    client = _client()
    results = []
    for item in items:
        slug = item.get("slug", "memory/unknown")
        content = item.get("content", "")
        tags = item.get("tags", ["memory"])
        results.append(client.put_page(slug, content, tags=tags))
    return {"ok": True, "indexed": len(results), "results": results}


def notify(status: str, errors: list[str]) -> dict[str, Any]:
    """Report sync status and indexing errors."""
    return {"ok": True, "status": status, "errors": errors}
